### ISSUE TITLE
How can I run TTRL for Qwen3-8B under  8 * NVIDIA A100 80GB GPUs

### ISSUE THREAD

**Issue by White1973** [PRIME-RL/TTRL#41]
Sorry to bother you.

I really appreciate your hard work for TTRL, which is a nice work for the LLM community.

As you mentioned in the paper, all experiments were conducted on 8 * NVIDIA A100 80GB GPUs. I want to inquire with you how I should reproduce TTRL for Qwen3-8B under  8 * NVIDIA A100 80GB GPUs. It always incurs the issue "CUDA out of Memory". 
I know it would be okay if I add more GPUs for experiments. But unfortunately, I only have  8 * NVIDIA A100 80GB GPUs.

**Comment by mootutu** [comment]
You can try to change the param: tensor_parallel_size, maybe it works😊！

**Comment by Gank0078** [comment]
> You can try to change the param: tensor_parallel_size, maybe it works😊！

Hi! I have similiar problem when I run bash examples/ttrl/Qwen2.5/aime.sh on 8*H100 GPUs. I increase actor_rollout_ref.rollout.tensor_model_parallel_size to 2, but it still OOM.

**Comment by mootutu** [comment]
> > You can try to change the param: tensor_parallel_size, maybe it works😊！
> 
> Hi! I have similiar problem when I run bash examples/ttrl/Qwen2.5/aime.sh on 8*H100 GPUs. I increase actor_rollout_ref.rollout.tensor_model_parallel_size to 2, but it still OOM.

I have also encountered this issue. Previously, when I was responding, I was using the old version of ttrl (verl0.2.0) code. When I switched to the new version of ttrl (verl0.4.1) code, I found that I also ran into the oom problem. My GPUs are 8×A800.

**Comment by BambiSheng** [comment]
Hi,  try decreasing `actor_rollout_ref.rollout.gpu_memory_utilization` to see if it resolves the OOM. All our training scripts have been tested on 8xA800 (80G).

**Comment by White1973** [comment]
It worked for me when I added "actor_rollout_ref.rollout.layered_summon=True \". 
When it still cannot work for some 8B-scale LLM (e.g., Qwen3-8B), I further added 
"actor_rollout_ref.model.lora_rank=128 \ 
and actor_rollout_ref.model.lora_alpha=128 \"
